---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release
  namespace: servicex-testing-1
spec:
  serviceAccountName: servicex-testing-1
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: '1.0.12'
  interval: 1m
  values:
    app:
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.ssl-hep.org

      ingress:
        enabled: true
        tls:
          enabled: true
          clusterIssuer: letsencrypt-prod

    codeGen:
      image: sslhep/servicex_code_gen_func_adl_xaod

    didFinder:
      rucio:
        enabled: true
        site: mwt2


    objectStore:
      enabled: true
      publicURL: xaod-minio.servicex.ssl-hep.org


    minio:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hosts:
        - "xaod-minio.servicex.ssl-hep.org"
        tls:
        - hosts:
          - xaod-minio.servicex.ssl-hep.org
          secretName: xaod-minio-tls

    postgres:
      enabled: true
    postgresql:
      persistence:
        enabled: true
        storageClass: rook-ceph-block
      master:
        nodeSelector:
          kernel-ml: "true"

    preflight:
      pullPolicy: Always

    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: '9419'
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: true
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-release-rabbitmq
        existingPasswordSecret: servicex-release-rabbitmq

    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      defaultTransformerImage: sslhep/servicex_func_adl_xaod_transformer:develop

    grid/ccount: ivukotic
    rbacEnabled: true
